-- Esquema de la base local en la versión 1 (antes de las unidades de venta).
-- Fixture de las pruebas de migración; no se edita.
CREATE TABLE "businesses" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "amount_mode" TEXT NOT NULL CHECK (amount_mode IN ('integer', 'two_decimals')), "quantity_mode" TEXT NOT NULL CHECK (quantity_mode IN ('integer', 'fractional')), "created_at" TEXT NOT NULL, PRIMARY KEY ("id"));
CREATE TABLE "clients" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL REFERENCES businesses (id), "name" TEXT NOT NULL, "character_id" TEXT NOT NULL, "skin_id" TEXT NOT NULL, "background_id" TEXT NOT NULL, "phone" TEXT NULL, "address" TEXT NULL, "note" TEXT NULL, "archived" INTEGER NOT NULL DEFAULT 0 CHECK ("archived" IN (0, 1)), "version" INTEGER NOT NULL DEFAULT 1, "created_by" TEXT NOT NULL, "created_at" TEXT NOT NULL, "updated_at" TEXT NOT NULL, PRIMARY KEY ("id"), UNIQUE ("id", "business_id"));
CREATE TABLE "fiado_items" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL REFERENCES businesses (id), "fiado_id" TEXT NOT NULL, "product_id" TEXT NULL, "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL CHECK (quantity > 0), "unit_price" INTEGER NOT NULL CHECK (unit_price > 0), "subtotal" INTEGER NOT NULL CHECK (subtotal > 0), PRIMARY KEY ("id"), FOREIGN KEY (fiado_id, business_id) REFERENCES fiados (id, business_id), FOREIGN KEY (product_id, business_id) REFERENCES products (id, business_id));
CREATE TABLE "fiados" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL REFERENCES businesses (id), "client_id" TEXT NOT NULL, "total" INTEGER NOT NULL CHECK (total > 0), "occurred_at" TEXT NOT NULL, "created_by" TEXT NOT NULL, "annulled_at" TEXT NULL, "annulled_by" TEXT NULL, "server_seq" INTEGER NULL, PRIMARY KEY ("id"), UNIQUE ("id", "business_id"), FOREIGN KEY (client_id, business_id) REFERENCES clients (id, business_id), CHECK ((annulled_at IS NULL) = (annulled_by IS NULL)));
CREATE TABLE "memberships" ("user_id" TEXT NOT NULL, "business_id" TEXT NOT NULL REFERENCES businesses (id), "role" TEXT NOT NULL CHECK (role IN ('owner', 'employee')), PRIMARY KEY ("user_id", "business_id"));
CREATE TABLE "outbox_ops" ("local_seq" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "op_id" TEXT NOT NULL UNIQUE, "business_id" TEXT NOT NULL REFERENCES businesses (id), "type" TEXT NOT NULL, "entity_id" TEXT NOT NULL, "payload" TEXT NOT NULL, "base_version" INTEGER NULL, "status" TEXT NOT NULL DEFAULT 'pending', "error_code" TEXT NULL, "created_at" TEXT NOT NULL, CHECK (type IN ('client.create', 'client.update', 'client.archive', 'client.restore', 'product.create', 'product.update', 'product.archive', 'fiado.create', 'payment.create', 'fiado.annul', 'payment.annul')), CHECK (status IN ('pending', 'sent', 'rejected')), CHECK ((status = 'rejected') = (error_code IS NOT NULL)));
CREATE TABLE "payments" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL REFERENCES businesses (id), "client_id" TEXT NOT NULL, "amount" INTEGER NOT NULL CHECK (amount > 0), "occurred_at" TEXT NOT NULL, "created_by" TEXT NOT NULL, "annulled_at" TEXT NULL, "annulled_by" TEXT NULL, "server_seq" INTEGER NULL, PRIMARY KEY ("id"), FOREIGN KEY (client_id, business_id) REFERENCES clients (id, business_id), CHECK ((annulled_at IS NULL) = (annulled_by IS NULL)));
CREATE TABLE "products" ("id" TEXT NOT NULL, "business_id" TEXT NOT NULL REFERENCES businesses (id), "name" TEXT NOT NULL, "price" INTEGER NOT NULL CHECK (price > 0), "archived" INTEGER NOT NULL DEFAULT 0 CHECK ("archived" IN (0, 1)), "version" INTEGER NOT NULL DEFAULT 1, "created_by" TEXT NOT NULL, "created_at" TEXT NOT NULL, PRIMARY KEY ("id"), UNIQUE ("id", "business_id"));
CREATE TABLE "sync_states" ("business_id" TEXT NOT NULL REFERENCES businesses (id), "cursor" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("business_id"), CHECK (cursor >= 0));
CREATE INDEX clients_business ON clients (business_id);
CREATE INDEX fiado_items_fiado ON fiado_items (fiado_id);
CREATE INDEX fiados_business ON fiados (business_id);
CREATE INDEX fiados_client ON fiados (client_id);
CREATE INDEX outbox_ops_business_status ON outbox_ops (business_id, status);
CREATE INDEX payments_business ON payments (business_id);
CREATE INDEX payments_client ON payments (client_id);
CREATE INDEX products_business ON products (business_id);
