// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulperia.Infrastructure.Persistence;

#nullable disable

namespace Pulperia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulperiaDbContext))]
    [Migration("20261008040246_ClientesYProductos")]
    partial class ClientesYProductos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmountMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amount_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LastSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_seq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QuantityMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quantity_mode");

                    b.HasKey("Id")
                        .HasName("pk_businesses");

                    b.ToTable("businesses", null, t =>
                        {
                            t.HasCheckConstraint("ck_businesses_amount_mode", "amount_mode IN ('integer', 'two_decimals')");

                            t.HasCheckConstraint("ck_businesses_last_seq", "last_seq >= 0");

                            t.HasCheckConstraint("ck_businesses_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_businesses_quantity_mode", "quantity_mode IN ('integer', 'fractional')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("BackgroundId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("background_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("SkinId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skin_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("Id", "BusinessId")
                        .HasName("uq_clients_id_business_id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_clients_business_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_clients_created_by");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("ck_clients_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_clients_note_length", "note IS NULL OR char_length(note) <= 300");

                            t.HasCheckConstraint("ck_clients_phone_format", "phone IS NULL OR phone ~ '^[2389][0-9]{7}$'");

                            t.HasCheckConstraint("ck_clients_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_invitations_business_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invitations_created_by");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_invitations_email_status");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_email_normalized", "email = lower(btrim(email)) AND btrim(email) <> ''");

                            t.HasCheckConstraint("ck_invitations_status", "status IN ('pending', 'accepted', 'rejected', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<bool>("FinalSyncUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("final_sync_used");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("UserId", "BusinessId")
                        .HasName("pk_memberships");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_memberships_business_id");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_memberships_removed_at", "status <> 'removed' OR removed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_memberships_role", "role IN ('owner', 'employee')");

                            t.HasCheckConstraint("ck_memberships_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("PreviousPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_price");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PriceChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_changed_at");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasAlternateKey("Id", "BusinessId")
                        .HasName("uq_products_id_business_id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_products_business_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_products_created_by");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_products_previous_price", "previous_price IS NULL OR previous_price > 0");

                            t.HasCheckConstraint("ck_products_price", "price > 0");

                            t.HasCheckConstraint("ck_products_price_history_pair", "(previous_price IS NULL) = (price_changed_at IS NULL)");

                            t.HasCheckConstraint("ck_products_unit", "unit IN ('unit', 'pound', 'ounce', 'kilo', 'dozen', 'liter', 'gallon', 'box', 'bag', 'pack')");

                            t.HasCheckConstraint("ck_products_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_normalized", "email = lower(btrim(email)) AND btrim(email) <> ''");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ClientEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_created_by");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_created_by");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_users_created_by");
                });
#pragma warning restore 612, 618
        }
    }
}
