// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulperia.Infrastructure.Persistence;

#nullable disable

namespace Pulperia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulperiaDbContext))]
    [Migration("20261008035800_IdentidadInicial")]
    partial class IdentidadInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmountMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amount_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LastSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_seq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QuantityMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quantity_mode");

                    b.HasKey("Id")
                        .HasName("pk_businesses");

                    b.ToTable("businesses", null, t =>
                        {
                            t.HasCheckConstraint("ck_businesses_amount_mode", "amount_mode IN ('integer', 'two_decimals')");

                            t.HasCheckConstraint("ck_businesses_last_seq", "last_seq >= 0");

                            t.HasCheckConstraint("ck_businesses_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_businesses_quantity_mode", "quantity_mode IN ('integer', 'fractional')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_invitations_business_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invitations_created_by");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_invitations_email_status");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_email_normalized", "email = lower(btrim(email)) AND btrim(email) <> ''");

                            t.HasCheckConstraint("ck_invitations_status", "status IN ('pending', 'accepted', 'rejected', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<bool>("FinalSyncUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("final_sync_used");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("UserId", "BusinessId")
                        .HasName("pk_memberships");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_memberships_business_id");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_memberships_removed_at", "status <> 'removed' OR removed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_memberships_role", "role IN ('owner', 'employee')");

                            t.HasCheckConstraint("ck_memberships_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_normalized", "email = lower(btrim(email)) AND btrim(email) <> ''");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_created_by");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
