// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pulperia.Infrastructure.Persistence;

#nullable disable

namespace Pulperia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PulperiaDbContext))]
    [Migration("20261008193229_CodigoDeInvitacion")]
    partial class CodigoDeInvitacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.AdminAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performed_by");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_audit");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_admin_audit_target_user_id");

                    b.ToTable("admin_audit", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_audit_action", "action IN ('reset_password')");

                            t.HasCheckConstraint("ck_admin_audit_performed_by", "btrim(performed_by) <> ''");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AmountMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amount_mode");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("LastSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_seq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("QuantityMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quantity_mode");

                    b.HasKey("Id")
                        .HasName("pk_businesses");

                    b.ToTable("businesses", null, t =>
                        {
                            t.HasCheckConstraint("ck_businesses_amount_mode", "amount_mode IN ('integer', 'two_decimals')");

                            t.HasCheckConstraint("ck_businesses_last_seq", "last_seq >= 0");

                            t.HasCheckConstraint("ck_businesses_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_businesses_quantity_mode", "quantity_mode IN ('integer', 'fractional')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ChangeLogEntity", b =>
                {
                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.HasKey("BusinessId", "Seq")
                        .HasName("pk_change_log");

                    b.ToTable("change_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_log_entity_type", "entity_type IN ('client', 'product', 'fiado', 'payment')");

                            t.HasCheckConstraint("ck_change_log_seq", "seq > 0");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("BackgroundId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("background_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("character_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("SkinId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skin_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("Id", "BusinessId")
                        .HasName("uq_clients_id_business_id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_clients_business_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_clients_created_by");

                    b.ToTable("clients", null, t =>
                        {
                            t.HasCheckConstraint("ck_clients_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_clients_note_length", "note IS NULL OR char_length(note) <= 300");

                            t.HasCheckConstraint("ck_clients_phone_format", "phone IS NULL OR phone ~ '^[2389][0-9]{7}$'");

                            t.HasCheckConstraint("ck_clients_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.FiadoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AnnulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("annulled_at");

                    b.Property<Guid?>("AnnulledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("annulled_by");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("Total")
                        .HasColumnType("bigint")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_fiados");

                    b.HasAlternateKey("Id", "BusinessId")
                        .HasName("uq_fiados_id_business_id");

                    b.HasIndex("AnnulledBy")
                        .HasDatabaseName("ix_fiados_annulled_by");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_fiados_created_by");

                    b.HasIndex("ClientId", "BusinessId")
                        .HasDatabaseName("ix_fiados_client_id_business_id");

                    b.ToTable("fiados", null, t =>
                        {
                            t.HasCheckConstraint("ck_fiados_annulment_pair", "(annulled_at IS NULL) = (annulled_by IS NULL)");

                            t.HasCheckConstraint("ck_fiados_total", "total > 0");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.FiadoItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FiadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("fiado_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<long>("Subtotal")
                        .HasColumnType("bigint")
                        .HasColumnName("subtotal");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_fiado_items");

                    b.HasIndex("FiadoId")
                        .HasDatabaseName("ix_fiado_items_fiado_id");

                    b.HasIndex("FiadoId", "BusinessId")
                        .HasDatabaseName("ix_fiado_items_fiado_id_business_id");

                    b.HasIndex("ProductId", "BusinessId")
                        .HasDatabaseName("ix_fiado_items_product_id_business_id");

                    b.ToTable("fiado_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_fiado_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_fiado_items_subtotal", "subtotal > 0");

                            t.HasCheckConstraint("ck_fiado_items_unit", "unit IN ('unit', 'pound', 'ounce', 'kilo', 'dozen', 'liter', 'gallon', 'box', 'bag', 'pack')");

                            t.HasCheckConstraint("ck_fiado_items_unit_price", "unit_price > 0");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_invitations_business_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_invitations_code");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_invitations_created_by");

                    b.HasIndex("Email", "Status")
                        .HasDatabaseName("ix_invitations_email_status");

                    b.ToTable("invitations", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitations_code_format", "code ~ '^[A-Z0-9]{8}$'");

                            t.HasCheckConstraint("ck_invitations_email_normalized", "email IS NULL OR (email = lower(btrim(email)) AND btrim(email) <> '')");

                            t.HasCheckConstraint("ck_invitations_status", "status IN ('pending', 'accepted', 'rejected', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<bool>("FinalSyncUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("final_sync_used");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("UserId", "BusinessId")
                        .HasName("pk_memberships");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_memberships_business_id");

                    b.ToTable("memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_memberships_removed_at", "status <> 'removed' OR removed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_memberships_role", "role IN ('owner', 'employee')");

                            t.HasCheckConstraint("ck_memberships_status", "status IN ('active', 'removed')");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("AnnulledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("annulled_at");

                    b.Property<Guid?>("AnnulledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("annulled_by");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasAlternateKey("Id", "BusinessId")
                        .HasName("uq_payments_id_business_id");

                    b.HasIndex("AnnulledBy")
                        .HasDatabaseName("ix_payments_annulled_by");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_payments_created_by");

                    b.HasIndex("ClientId", "BusinessId")
                        .HasDatabaseName("ix_payments_client_id_business_id");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount > 0");

                            t.HasCheckConstraint("ck_payments_annulment_pair", "(annulled_at IS NULL) = (annulled_by IS NULL)");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ProcessedOpEntity", b =>
                {
                    b.Property<Guid>("OpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("op_id");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.HasKey("OpId")
                        .HasName("pk_processed_ops");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_processed_ops_business_id");

                    b.ToTable("processed_ops", null, t =>
                        {
                            t.HasCheckConstraint("ck_processed_ops_result", "btrim(result) <> ''");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("PreviousPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("previous_price");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PriceChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_changed_at");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasAlternateKey("Id", "BusinessId")
                        .HasName("uq_products_id_business_id");

                    b.HasIndex("BusinessId")
                        .HasDatabaseName("ix_products_business_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_products_created_by");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_name_required", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_products_previous_price", "previous_price IS NULL OR previous_price > 0");

                            t.HasCheckConstraint("ck_products_price", "price > 0");

                            t.HasCheckConstraint("ck_products_price_history_pair", "(previous_price IS NULL) = (price_changed_at IS NULL)");

                            t.HasCheckConstraint("ck_products_unit", "unit IN ('unit', 'pound', 'ounce', 'kilo', 'dozen', 'liter', 'gallon', 'box', 'bag', 'pack')");

                            t.HasCheckConstraint("ck_products_version", "version >= 1");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("RefreshExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_expires_at");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_sessions_access_token_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_sessions_refresh_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sessions_user_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email_normalized", "email = lower(btrim(email)) AND btrim(email) <> ''");
                        });
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.AdminAuditEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_audit_users_target_user_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ChangeLogEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_change_log_businesses_business_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ClientEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_users_created_by");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.FiadoEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AnnulledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fiados_users_annulled_by");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiados_users_created_by");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.ClientEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "BusinessId")
                        .HasPrincipalKey("Id", "BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiados_clients_client_id_business_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.FiadoItemEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.FiadoEntity", null)
                        .WithMany()
                        .HasForeignKey("FiadoId", "BusinessId")
                        .HasPrincipalKey("Id", "BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fiado_items_fiados_fiado_id_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.ProductEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductId", "BusinessId")
                        .HasPrincipalKey("Id", "BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fiado_items_products_product_id_business_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.InvitationEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_created_by");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.MembershipEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.PaymentEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AnnulledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_payments_users_annulled_by");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_users_created_by");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.ClientEntity", null)
                        .WithMany()
                        .HasForeignKey("ClientId", "BusinessId")
                        .HasPrincipalKey("Id", "BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_clients_client_id_business_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ProcessedOpEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_processed_ops_businesses_business_id");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.BusinessEntity", null)
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_businesses_business_id");

                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_users_created_by");
                });

            modelBuilder.Entity("Pulperia.Infrastructure.Persistence.Entities.SessionEntity", b =>
                {
                    b.HasOne("Pulperia.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
